"""create departments and production lines

Revision ID: d0babbe87eec
Revises: 20260804_0002
Create Date: 2026-08-04 22:05:51.311721
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd0babbe87eec'
down_revision: str | None = '20260804_0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id', 'code', name='uq_departments_factory_code')
    )
    op.create_index(op.f('ix_departments_factory_id'), 'departments', ['factory_id'], unique=False)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('production_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id', 'code', name='uq_production_lines_factory_code')
    )
    op.create_index(op.f('ix_production_lines_department_id'), 'production_lines', ['department_id'], unique=False)
    op.create_index(op.f('ix_production_lines_factory_id'), 'production_lines', ['factory_id'], unique=False)
    op.create_index(op.f('ix_production_lines_id'), 'production_lines', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_lines_id'), table_name='production_lines')
    op.drop_index(op.f('ix_production_lines_factory_id'), table_name='production_lines')
    op.drop_index(op.f('ix_production_lines_department_id'), table_name='production_lines')
    op.drop_table('production_lines')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_factory_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
